### ISSUE TITLE
Candidate name display not user-friendly

### ISSUE THREAD

**Issue by B-Dionysus** [B-Dionysus/project1-Election#24]
Candidate are displayed last name first (eg., Smith, William), but it would be better if they were displayed in human-standard (William Smith)

**Comment by anushri20** [comment]
Hi, Can I work on this?

**Comment by B-Dionysus** [comment]
Dear Anushri,
I'm so sorry, I think I used the wrong label for this! This is just for a student project, so I think we need to do all the coding ourselves. But thank you so much for the offer!

-=Benjamin

**Comment by B-Dionysus** [comment]
// Unfortunately, the data may include honorifics at the end, without demarcation
        // e.g. "Biden, Joseph R Jr," and these appear to be arbitrary
        // e.g. "Jones, Take Mr.", so I don't think there's a clear way to sort them.
        // Also, while I'm here, only of the presidential candidates is listed as
        // "Title, Sheila Samm Mpresident". This is how they appear in the data set from the FEC.
